/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzleDeslizanteV2;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;

/**
 *
 * @author chkds
 */
public class Puntaje extends javax.swing.JFrame {
    
    int numeroJugadores =0;
    String textoGuardado;
    String filtro = "";
    public ArrayList<Jugador> jugadorArrayList=new ArrayList<Jugador>();
    
    public Puntaje() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
       
      panelScore.setSize(this.getSize());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScore = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPuntaje = new javax.swing.JTextArea();
        btnAtrasP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cuadroFiltro = new javax.swing.JTextField();
        numeroDeJugadores = new javax.swing.JTextField();
        btnGuardarLista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Tabla de Puntuaciones");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelScore.setBackground(new java.awt.Color(51, 51, 51));
        panelScore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Puntuaciones");
        panelScore.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 27, -1, -1));

        jScrollPane1.setOpaque(false);

        panelPuntaje.setBackground(new java.awt.Color(51, 51, 51));
        panelPuntaje.setColumns(20);
        panelPuntaje.setForeground(new java.awt.Color(204, 204, 204));
        panelPuntaje.setRows(5);
        panelPuntaje.setOpaque(false);
        jScrollPane1.setViewportView(panelPuntaje);

        panelScore.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 89, 474, 223));

        btnAtrasP.setBackground(new java.awt.Color(51, 51, 51));
        btnAtrasP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtrasP.setForeground(new java.awt.Color(204, 204, 204));
        btnAtrasP.setText("Atrás");
        btnAtrasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasPActionPerformed(evt);
            }
        });
        panelScore.add(btnAtrasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Número de ranking:");
        panelScore.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Filtrar por nombre:");
        panelScore.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        cuadroFiltro.setBackground(new java.awt.Color(51, 51, 51));
        cuadroFiltro.setForeground(new java.awt.Color(204, 204, 204));
        cuadroFiltro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cuadroFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroFiltroActionPerformed(evt);
            }
        });
        panelScore.add(cuadroFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, -1));

        numeroDeJugadores.setBackground(new java.awt.Color(51, 51, 51));
        numeroDeJugadores.setForeground(new java.awt.Color(204, 204, 204));
        numeroDeJugadores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroDeJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeJugadoresActionPerformed(evt);
            }
        });
        panelScore.add(numeroDeJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 130, -1));

        btnGuardarLista.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardarLista.setForeground(new java.awt.Color(204, 204, 204));
        btnGuardarLista.setText("Guardar esta lista");
        btnGuardarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarListaActionPerformed(evt);
            }
        });
        panelScore.add(btnGuardarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondos/fondo1.jpg"))); // NOI18N
        panelScore.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        getContentPane().add(panelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void recuperarRanking(){
        try {
            FileInputStream fis3=new FileInputStream("ranking.txt");
            BufferedInputStream bis3=new BufferedInputStream(fis3);
            ObjectInputStream ois3=new ObjectInputStream(bis3);
            jugadorArrayList=(ArrayList<Jugador>) ois3.readObject();

            ois3.close();


        } catch (IOException e) {
            e.printStackTrace();
        }catch (ClassNotFoundException ex){
            ex.printStackTrace();
        }
}  
    public void setPuntaje(){
       String imprime;
             String espacio="   ";
            for (int i = 0; i < jugadorArrayList.size()-1; i++) {
            for (int j = 0; j <jugadorArrayList.size()-1; j++) {
                Jugador a1=jugadorArrayList.get(j);
                Jugador a2=jugadorArrayList.get(j+1);
                if(a1.getPuntaje()>a2.getPuntaje()){
                    Jugador aux=jugadorArrayList.get(j);
                    jugadorArrayList.set(j,jugadorArrayList.get(j+1));
                    jugadorArrayList.set(j+1,aux);
                }
            }

        }
            if (numeroJugadores>jugadorArrayList.size()) {
                numeroJugadores=jugadorArrayList.size();
        }
            if(numeroDeJugadores.getText().equals("")){
                numeroJugadores=jugadorArrayList.size();
            }

        String texto = "nro       Jugador        Movimientos      Tiempo        Puntaje";
        texto += "\n";
        texto+="--------------------------------------------------------------------------------";
        texto+="\n";
        for (int i = 0; i < numeroJugadores; i++) {
            if (filtro.equals("")|| filtro.equalsIgnoreCase(jugadorArrayList.get(i).nombre)){
                if (i>8) {
                    espacio=" ";
                }
            texto= texto + (i+1) +espacio+jugadorArrayList.get(i).toString()+"           "+jugadorArrayList.get(i).getPuntaje();
            texto += "\n";
            texto+="-------------------------------------------------------------------------------";
            texto+="\n";
            }
        }
        panelPuntaje.setText(texto);
        textoGuardado=texto;
    }
    
    public void insertarJugador(Jugador jugadorActual){
        jugadorArrayList.add(jugadorActual);
    }
    
    private void btnAtrasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasPActionPerformed

    private void cuadroFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroFiltroActionPerformed
        // TODO add your handling code here:
        filtro = cuadroFiltro.getText();
        numeroJugadores = jugadorArrayList.size();
        numeroDeJugadores.setText("");
        setPuntaje();
    }//GEN-LAST:event_cuadroFiltroActionPerformed

    private void numeroDeJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeJugadoresActionPerformed
        // TODO add your handling code here:
        numeroJugadores= Integer.parseInt(numeroDeJugadores.getText());
        filtro = "";
        cuadroFiltro.setText("");
        setPuntaje();
    }//GEN-LAST:event_numeroDeJugadoresActionPerformed

    private void btnGuardarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarListaActionPerformed
        // TODO add your handling code here:
        try{
            BufferedWriter bw = new BufferedWriter(new FileWriter("puntajes.txt"));
            bw.write(textoGuardado);
            bw.newLine();
            bw.close();
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_btnGuardarListaActionPerformed
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puntaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puntaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasP;
    private javax.swing.JButton btnGuardarLista;
    private javax.swing.JTextField cuadroFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numeroDeJugadores;
    private javax.swing.JTextArea panelPuntaje;
    private javax.swing.JPanel panelScore;
    // End of variables declaration//GEN-END:variables
}
