/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzleDeslizanteV2;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.FileChooserUI;

/**
 *
 * @author adanllanos//////////////////////////////////////
 */
public class Seleccionar extends javax.swing.JFrame {

    File archivo;
    private int dificultadX = 0;
    private int dificultadY = 0;
    
    public String nombreJ="";
    private Object FileUtils;
    private   String imagen = "";
    private Boolean seleccionadoImagenPersonalizada=false;
    public Interfaz interfaz1;
    public int index;
    public ArrayList<Interfaz> lista = new ArrayList();
    public JTabbedPane tab=new JTabbedPane();
    public int counter;
    public boolean bb=false;
    public Seleccionar() {
        initComponents();
        colocarImagenes();
        setLocationRelativeTo(null);
        //this.setSize(700, 700);
        this.setTitle("Slide Puzzle");
        setResizable(false);
        ventanaSelec.setVisible(false);
        imagenActual.setVisible(false);
    }
    
     public Seleccionar(int dX, int dY, String nombre, String imagen,Interfaz interfaz1){
        dificultadX = dX;
        dificultadY = dY;
        nombreJ = nombre;
        this.imagen = imagen;
        this.interfaz1=interfaz1;
        initComponents();
        colocarImagenes();
        setLocationRelativeTo(null);
        this.setTitle("Slide Puzzle");
        setResizable(false);
        ventanaSelec.setVisible(false);
        btnRegresar.setEnabled(true);
    
    }
    
    
    
    public  String getImagen(){
        return this.imagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING:. Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        ventanas = new javax.swing.JPanel();
        ventanaInicio = new javax.swing.JPanel();
        btnEmpezar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnReanudar = new javax.swing.JButton();
        btnReanudar1 = new javax.swing.JButton();
        btnPuntajes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ventanaSelec = new javax.swing.JPanel();
        textNombre1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        imagen2 = new javax.swing.JButton();
        imagen1 = new javax.swing.JButton();
        imagen3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JButtonElegir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAtrasD = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelDif1 = new javax.swing.JPanel();
        jButton3x3 = new javax.swing.JButton();
        jButton4x4 = new javax.swing.JButton();
        jButton5x5 = new javax.swing.JButton();
        jButton6x6 = new javax.swing.JButton();
        jButton7x7 = new javax.swing.JButton();
        jButton8x8 = new javax.swing.JButton();
        selectorDif2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selectorDif1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        imagenActual = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fondoConfig = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventanaInicio.setVerifyInputWhenFocusTarget(false);
        ventanaInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpezar.setBackground(new java.awt.Color(51, 51, 51));
        btnEmpezar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEmpezar.setForeground(new java.awt.Color(204, 204, 204));
        btnEmpezar.setText("Jugar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        ventanaInicio.add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 160, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Slide Puzzle");
        ventanaInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        ventanaInicio.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 160, 50));

        btnReanudar.setBackground(new java.awt.Color(51, 51, 51));
        btnReanudar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnReanudar.setForeground(new java.awt.Color(204, 204, 204));
        btnReanudar.setText("Cargar Partida");
        btnReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReanudarActionPerformed(evt);
            }
        });
        ventanaInicio.add(btnReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 160, 50));

        btnReanudar1.setBackground(new java.awt.Color(51, 51, 51));
        btnReanudar1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnReanudar1.setForeground(new java.awt.Color(204, 204, 204));
        btnReanudar1.setText("Ayuda");
        btnReanudar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReanudar1ActionPerformed(evt);
            }
        });
        ventanaInicio.add(btnReanudar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 160, 50));

        btnPuntajes.setBackground(new java.awt.Color(51, 51, 51));
        btnPuntajes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPuntajes.setForeground(new java.awt.Color(204, 204, 204));
        btnPuntajes.setText("Puntajes");
        btnPuntajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntajesActionPerformed(evt);
            }
        });
        ventanaInicio.add(btnPuntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 160, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondos/fondosjpg.jpg"))); // NOI18N
        ventanaInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 660));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ventanaInicio.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 160, 50));

        ventanaSelec.setBackground(new java.awt.Color(51, 51, 51));
        ventanaSelec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ventanaSelec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNombre1.setBackground(new java.awt.Color(51, 51, 51));
        textNombre1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        textNombre1.setForeground(new java.awt.Color(204, 204, 204));
        textNombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNombre1.setText("Nombre Jugador");
        textNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombre1ActionPerformed(evt);
            }
        });
        ventanaSelec.add(textNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 108, 606, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setOpaque(false);

        imagen2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imagen2.setBorderPainted(false);
        imagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagen2ActionPerformed(evt);
            }
        });

        imagen1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imagen1.setBorderPainted(false);
        imagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagen1ActionPerformed(evt);
            }
        });

        imagen3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imagen3.setBorderPainted(false);
        imagen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagen3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Puzzle");

        JButtonElegir.setBackground(new java.awt.Color(51, 51, 51));
        JButtonElegir.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        JButtonElegir.setForeground(new java.awt.Color(204, 204, 204));
        JButtonElegir.setText("Puzzle Personalizado");
        JButtonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JButtonElegir)
                                .addGap(18, 18, 18)))
                        .addGap(25, 25, 25)
                        .addComponent(imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagen3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(JButtonElegir)
                .addGap(18, 18, 18))
        );

        ventanaSelec.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 700, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Configuración del Puzzle");
        ventanaSelec.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nombre del Jugador");
        ventanaSelec.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 64, -1, -1));

        btnAtrasD.setBackground(new java.awt.Color(51, 51, 51));
        btnAtrasD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtrasD.setForeground(new java.awt.Color(204, 204, 204));
        btnAtrasD.setText("Atrás");
        btnAtrasD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasDActionPerformed(evt);
            }
        });
        ventanaSelec.add(btnAtrasD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 110, 40));

        jButtonAceptar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAceptar.setText("Empezar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        ventanaSelec.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 110, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setAutoscrolls(true);
        jPanel1.setOpaque(false);

        panelDif1.setBackground(new java.awt.Color(51, 51, 51));

        jButton3x3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3x3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3x3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3x3.setText("3x3");
        jButton3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x3ActionPerformed(evt);
            }
        });
        panelDif1.add(jButton3x3);

        jButton4x4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4x4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4x4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4x4.setText("4x4");
        jButton4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x4ActionPerformed(evt);
            }
        });
        panelDif1.add(jButton4x4);

        jButton5x5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5x5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5x5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5x5.setText("5x5");
        jButton5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x5ActionPerformed(evt);
            }
        });
        panelDif1.add(jButton5x5);

        jButton6x6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6x6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6x6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6x6.setText("6x6");
        jButton6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x6ActionPerformed(evt);
            }
        });
        panelDif1.add(jButton6x6);

        jButton7x7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7x7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7x7.setForeground(new java.awt.Color(204, 204, 204));
        jButton7x7.setText("7x7");
        jButton7x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x7ActionPerformed(evt);
            }
        });
        panelDif1.add(jButton7x7);

        jButton8x8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8x8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8x8.setForeground(new java.awt.Color(204, 204, 204));
        jButton8x8.setText("8x8");
        jButton8x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x8ActionPerformed(evt);
            }
        });
        panelDif1.add(jButton8x8);

        selectorDif2.setBackground(new java.awt.Color(51, 51, 51));
        selectorDif2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectorDif2.setForeground(new java.awt.Color(204, 204, 204));
        selectorDif2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Dificultad");

        selectorDif1.setBackground(new java.awt.Color(51, 51, 51));
        selectorDif1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectorDif1.setForeground(new java.awt.Color(204, 204, 204));
        selectorDif1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("X");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Dificultad Personalizada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(panelDif1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59)
                        .addComponent(selectorDif2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(selectorDif1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectorDif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorDif2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        ventanaSelec.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 700, 110));

        imagenActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenActualActionPerformed(evt);
            }
        });
        ventanaSelec.add(imagenActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 130, 90));

        btnRegresar.setBackground(new java.awt.Color(51, 51, 51));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(204, 204, 204));
        btnRegresar.setText("Regresar a la Partida");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        ventanaSelec.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 200, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Imagen");
        ventanaSelec.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 70, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Actual");
        ventanaSelec.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 70, -1));

        fondoConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondos/Cool-Black-Backgrounds-HD-wallpaper.jpg"))); // NOI18N
        fondoConfig.setText("jLabel7");
        ventanaSelec.add(fondoConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 650));

        javax.swing.GroupLayout ventanasLayout = new javax.swing.GroupLayout(ventanas);
        ventanas.setLayout(ventanasLayout);
        ventanasLayout.setHorizontalGroup(
            ventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 749, Short.MAX_VALUE)
            .addGroup(ventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanasLayout.createSequentialGroup()
                    .addComponent(ventanaSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ventanasLayout.setVerticalGroup(
            ventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 653, Short.MAX_VALUE)
            .addGroup(ventanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ventanaSelec, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void JButtonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonElegirActionPerformed
        // TODO add your handling code here:
        int resultado;
        Buscador buscador = new Buscador();
        FileNameExtensionFilter formato = new FileNameExtensionFilter("JPG, PNG y GIF", "jpg", "png", "gif");
        buscador.buscadorI.setFileFilter(formato);
        resultado = buscador.buscadorI.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            archivo = buscador.buscadorI.getSelectedFile();
            imagen=archivo.getAbsolutePath();
            seleccionadoImagenPersonalizada=true;
            JOptionPane.showMessageDialog(this, "Imagen seleccionada con éxito");
            
        }
    }//GEN-LAST:event_JButtonElegirActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        //seleccionarD(dificultad);
        if(bb==false){
        if(!selectorDif1.getText().isEmpty() && !selectorDif2.getText().isEmpty()){
            dificultadY = Integer.parseInt(selectorDif1.getText()); 
            dificultadX = Integer.parseInt(selectorDif2.getText());
        }
        
        if(dificultadY > 1 && dificultadY <= 10 && dificultadX > 1 && dificultadX <= 10){
            
        
        if (imagen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No seleccionaste una imágen");
        } 
       
        else {
            try {
                SplitImage.createFiles(imagen, dificultadX, dificultadY);
            } catch (IOException e) {
                e.printStackTrace();
            }
            String test = "asd";
            this.setVisible(false);
            nombreJ=textNombre1.getText();
            Interfaz interfaz = new Interfaz(dificultadX, dificultadY, nombreJ,imagen);
            interfaz.setVisible(true);
            
        }
        } else if(dificultadX == 0 || dificultadY == 0){
            JOptionPane.showMessageDialog(this, "No seleccionaste una dificultad");
        }
        else{
            JOptionPane.showMessageDialog(this, "La dificultad debe estar entre 2 y 10");
        }  
        }else{
            
            try {
                SplitImage.createFiles(imagen, dificultadX, dificultadY);
            } catch (IOException e) {
                e.printStackTrace();
            }
            //this.setVisible(false);
            //interfaz1.recivirDatos(dificultadX, dificultadY, nombreJ,imagen);
            
            
            
            
            
        try {
                SplitImage.createFiles(imagen, dificultadX, dificultadY);
            } catch (IOException e) {
                e.printStackTrace();
            }
            this.setVisible(false);
            nombreJ=textNombre1.getText();
            Interfaz interfaz = new Interfaz(dificultadX, dificultadY, nombreJ,imagen);
            interfaz.btnAtras.setVisible(false);
            interfaz1.counter++;
            interfaz1.addTabPanel(interfaz.jPanel2, interfaz.nombreJ);
            interfaz1.lista.add(interfaz);
            //interfaz1.tabPane=this.tab;
            this.setVisible(false);
            interfaz.setVisible(false);
            interfaz1.setVisible(true);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void btnAtrasDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasDActionPerformed
        //ventanas.setSelectedComponent(ventanaInicio);
        ventanaSelec.setVisible(false);
        ventanaInicio.setVisible(true);
    }//GEN-LAST:event_btnAtrasDActionPerformed

    private void deshabilitarDificultad(JButton btn1, JButton btn2){
        
        if(btn1.isEnabled() && !btn2.isEnabled()){
        
        
        jButton3x3.setEnabled(true);
        jButton4x4.setEnabled(true);
        jButton5x5.setEnabled(true);
        jButton6x6.setEnabled(true);
        jButton7x7.setEnabled(true);
        jButton8x8.setEnabled(true);
        }else{
       
        jButton3x3.setEnabled(false);
        jButton4x4.setEnabled(false);
        jButton5x5.setEnabled(false);
        jButton6x6.setEnabled(false);
        jButton7x7.setEnabled(false);
        jButton8x8.setEnabled(false);
        btn1.setEnabled(true);
        }
    }
    private void jButton8x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x8ActionPerformed
       deshabilitarDificultad(jButton8x8, jButton7x7);
        selectorDif1.setText(String.valueOf(8));
        selectorDif2.setText(String.valueOf(8));
        dificultadX = 8;
        dificultadY = 8;
    }//GEN-LAST:event_jButton8x8ActionPerformed

    private void jButton7x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x7ActionPerformed
        deshabilitarDificultad(jButton7x7, jButton8x8);
       selectorDif1.setText(String.valueOf(7));
        selectorDif2.setText(String.valueOf(7));
        dificultadX = 7;
        dificultadY = 7;
    }//GEN-LAST:event_jButton7x7ActionPerformed

    private void jButton6x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x6ActionPerformed
         deshabilitarDificultad(jButton6x6, jButton7x7);
       selectorDif1.setText(String.valueOf(6));
        selectorDif2.setText(String.valueOf(6));
        dificultadX = 6;
        dificultadY = 6;
    }//GEN-LAST:event_jButton6x6ActionPerformed

    private void jButton5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x5ActionPerformed
       deshabilitarDificultad(jButton5x5, jButton7x7);
        selectorDif1.setText(String.valueOf(5));
        selectorDif2.setText(String.valueOf(5));
        dificultadX = 5;
        dificultadY = 5;
    }//GEN-LAST:event_jButton5x5ActionPerformed

    private void jButton4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x4ActionPerformed
        deshabilitarDificultad(jButton4x4, jButton7x7);
        selectorDif1.setText(String.valueOf(4));
        selectorDif2.setText(String.valueOf(4));
        dificultadX = 4;
        dificultadY = 4;
    }//GEN-LAST:event_jButton4x4ActionPerformed

    private void jButton3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x3ActionPerformed
        deshabilitarDificultad(jButton3x3, jButton7x7);
        selectorDif1.setText(String.valueOf(3));
        selectorDif2.setText(String.valueOf(3));
        dificultadX = 3;
        dificultadY = 3;
    }//GEN-LAST:event_jButton3x3ActionPerformed

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
       ventanaInicio.setVisible(false);
       ventanaSelec.setVisible(true);
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void textNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombre1ActionPerformed

    }//GEN-LAST:event_textNombre1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void imagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagen2ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        
       
        if(!imagen1.isEnabled() && !imagen3.isEnabled()){
            imagen = null;
            imagen1.setEnabled(true);
            imagen3.setEnabled(true);
        }else{
            imagen = "src/images/Galeria/Imagen2.jpg";
            imagen1.setEnabled(false);
            imagen3.setEnabled(false);
        }
    }//GEN-LAST:event_imagen2ActionPerformed

    private void imagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagen1ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        
       if(!imagen2.isEnabled() && !imagen3.isEnabled()){
           imagen = null; 
           imagen2.setEnabled(true);
            imagen3.setEnabled(true);
        }else{
           imagen = "src/images/Galeria/Imagen1.jpg";
             imagen2.setEnabled(false);
            imagen3.setEnabled(false);
        }
    }//GEN-LAST:event_imagen1ActionPerformed

    private void imagen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagen3ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        
       
        if(!imagen1.isEnabled() && !imagen2.isEnabled()){
            imagen = null;
            imagen1.setEnabled(true);
            imagen2.setEnabled(true);
        }else{
            imagen = "src/images/Galeria/Imagen3.jpg";
             imagen1.setEnabled(false);
            imagen2.setEnabled(false);
        }
    }//GEN-LAST:event_imagen3ActionPerformed

    private void btnReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReanudarActionPerformed
       int resultado;
       
        Buscador buscador = new Buscador();
        FileNameExtensionFilter formato = new FileNameExtensionFilter("TXT", "txt");
        buscador.buscadorI.setFileFilter(formato);
        resultado = buscador.buscadorI.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            archivo = buscador.buscadorI.getSelectedFile();
        
        try {
                FileInputStream fis1=new FileInputStream(archivo.getAbsolutePath());
                
                BufferedInputStream bis1=new BufferedInputStream(fis1);
                ObjectInputStream ois1=new ObjectInputStream(bis1);
                CargarPartida partidaRecuperada=(CargarPartida) ois1.readObject();
                ois1.close();
                DatosGuardados datosRecuperados=partidaRecuperada.getDatosGuardados();
                Juego juegoRecuperado=partidaRecuperada.getJuego();

                String a=datosRecuperados.imagenDelJuego;
                int b=datosRecuperados.dificultadX;
                int c=datosRecuperados.dificultadY;
                SplitImage.createFiles(a,b,c);

            this.setVisible(false);
            Interfaz interfaz = new Interfaz(b, c, datosRecuperados.nombreJugador, datosRecuperados.imagenDelJuego);
            interfaz.setVisible(true);
            interfaz.setDatosGuardados(datosRecuperados);
            interfaz.setJuego(juegoRecuperado);
            interfaz.pausarJuego();
            interfaz.actualizarEtiquetaPasos();

        } catch (IOException e) {
            e.printStackTrace();
        }catch (ClassNotFoundException ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnReanudarActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnReanudar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReanudar1ActionPerformed
        // TODO add your handling code here:
        Ayuda help = new Ayuda();
        help.setVisible(true);
    }//GEN-LAST:event_btnReanudar1ActionPerformed

    private void btnPuntajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntajesActionPerformed
        // TODO add your handling code here:
        Puntaje puntaje = new Puntaje();
        puntaje.setVisible(true);
        puntaje.recuperarRanking();
        puntaje.setPuntaje();
    }//GEN-LAST:event_btnPuntajesActionPerformed

    private void imagenActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagenActualActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        interfaz1.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed
               

    public void actualizarDatos(){
        selectorDif1.setText(String.valueOf(dificultadX));
        selectorDif2.setText(String.valueOf(dificultadY));
        textNombre1.setText(nombreJ);
        imagenActual.setVisible(true);
        ImageIcon iconobtn1 = new ImageIcon(imagen);
        ImageIcon iconobtnEscalado = new ImageIcon(iconobtn1.getImage().getScaledInstance(imagenActual.getWidth(), imagenActual.getHeight()+10, Image.SCALE_DEFAULT));
        imagenActual.setIcon(iconobtnEscalado);
    
    }
    
    public void colocarImagenes() {

        ImageIcon iconobtn1 = new ImageIcon("src/images/Galeria/Imagen1.jpg");
        ImageIcon iconobtnEscalado1 = new ImageIcon(iconobtn1.getImage().getScaledInstance(imagen1.getWidth(), imagen1.getHeight()+10, Image.SCALE_DEFAULT));
        imagen1.setIcon(iconobtnEscalado1);
        ImageIcon iconobtn2 = new ImageIcon("src/images/Galeria/Imagen2.jpg");
        ImageIcon iconobtnEscalado2 = new ImageIcon(iconobtn2.getImage().getScaledInstance(imagen3.getWidth(), imagen3.getHeight()+10, Image.SCALE_DEFAULT));
        imagen2.setIcon(iconobtnEscalado2);
        ImageIcon iconobtn3 = new ImageIcon(("src/images/Galeria/Imagen3.jpg"));
        ImageIcon iconobtnEscalado3 = new ImageIcon(iconobtn3.getImage().getScaledInstance(imagen3.getWidth(), imagen3.getHeight()+10, Image.SCALE_DEFAULT));
        imagen3.setIcon(iconobtnEscalado3);
    }

    private void seleccionarD(int dificultad) {
        if (dificultad >= 3 || dificultad <= 8) {
            this.setVisible(false);
            Interfaz interfaz = new Interfaz(dificultadX, dificultadY, nombreJ,imagen);
            interfaz.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //JOptionPane.showInputDialog("nombre del jugador");
                new Seleccionar().setVisible(true);

            }
        });

    }

    public Icon setIcono(String archivo, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(archivo));
        int ancho = boton.getWidth();
        int altura = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, altura, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonElegir;
    public javax.swing.JButton btnAtrasD;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnPuntajes;
    private javax.swing.JButton btnReanudar;
    private javax.swing.JButton btnReanudar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondoConfig;
    private javax.swing.JButton imagen1;
    private javax.swing.JButton imagen2;
    private javax.swing.JButton imagen3;
    private javax.swing.JButton imagenActual;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3x3;
    private javax.swing.JButton jButton4x4;
    private javax.swing.JButton jButton5x5;
    private javax.swing.JButton jButton6x6;
    private javax.swing.JButton jButton7x7;
    private javax.swing.JButton jButton8x8;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panelDif1;
    private javax.swing.JTextField selectorDif1;
    private javax.swing.JTextField selectorDif2;
    private javax.swing.JTextField textNombre1;
    public javax.swing.JPanel ventanaInicio;
    public javax.swing.JPanel ventanaSelec;
    private javax.swing.JPanel ventanas;
    // End of variables declaration//GEN-END:variables
}
